Pes 458 print order collection
Zasilkovna/WooCommerce pull request #114
Opened 2021-12-02 11:32 UTC by FJiskra

2021-12-02 14:12 UTC, jan-potuznik-z commented on packetery/src/Packetery/Module/Adapter.php
> +	public static function getAllUniquePostMeta( int $postId ): array {
Jestli vidím dobře, jde o nepoužívanou metodu a třídu. Tedy odstranit?

2021-12-02 14:12 UTC, jan-potuznik-z commented on packetery/src/Packetery/Module/Order/Repository.php
> +				$orderEntities[ $order->getNumber() ] = $order;
Tímto se metoda stává nepoužitelnou pro načtení nepodaných objednávek. Prosím zohlednit v názvu.

2021-12-02 14:12 UTC, jan-potuznik-z commented on packetery/src/Packetery/Module/Order/Entity.php
> +	public function getFormattedShippingFullname(): string {
Nepoužitá metoda? Prosím odstranit, pokud tomu tak je.

2021-12-03 07:37 UTC, FJiskra commented on packetery/src/Packetery/Module/Order/Repository.php
> +				$orderEntities[ $order->getNumber() ] = $order;
getNumber() vrací id post entity. ID je nenullable. Metoda čte pouze z databáze.

2021-12-03 08:04 UTC, jan-potuznik-z commented on packetery/src/Packetery/Module/Order/Repository.php
> +				$orderEntities[ $order->getNumber() ] = $order;
getNumber() vrací id zásilky a je nullable.

2021-12-06 17:10 UTC, packeta requested changes

2021-12-06 17:10 UTC, packeta commented on packetery/template/order/collection-print.latte
> +                    END
Jak budeme pak tento řetězec překládat ?

2021-12-09 07:46 UTC, merged