Pes 480 sender description update
Zasilkovna/WooCommerce pull request #125
Opened 2022-01-06 11:56 UTC by FJiskra

2022-01-06 12:31 UTC, packeta requested changes

2022-01-06 12:31 UTC, packeta commented on packetery/languages/packetery-en_US.po
> +msgid "senderDescription"
do překladu nedávejme prosím html tagy.

2022-01-07 08:13 UTC, FJiskra commented on packetery/languages/packetery-en_US.po
> +msgid "senderDescription"
upraveno

2022-01-07 10:14 UTC, packeta requested changes

2022-01-07 10:14 UTC, packeta commented on packetery/languages/packetery-en_US.po
> +"'Indication'."
vkládání url udělejme prosím tak, radí dokumentace ? https://developer.wordpress.org/plugins/internationalization/security/#top
pro překladatele můžeš přidat komentář, kde vysvětlíš co obsahují jednotlivé zástupné znaky.

2022-01-07 14:26 UTC, merged