PES-919 Calculation of exceeding the Free shipping limit without discount from coupons
Zasilkovna/WooCommerce pull request #273
Opened 2022-09-08 14:27 UTC by Mrakor

2022-09-09 07:09 UTC, zemekoule requested changes

2022-09-09 07:09 UTC, zemekoule commented on src/Packetery/Module/Checkout.php
> +		$cartContentPrice  = WC()->cart->get_cart_contents_total();
Při volání metody get_cart_contents_total() není podle tebe nutné přetypovat na float ? Tato metoda volá stejný filtr, jako metoda get_subtotal() ve stejné třídě. Zde jsme proto vytvářeli metodu getCartPrice().

2022-09-12 07:29 UTC, jan-potuznik-z commented on src/Packetery/Module/Checkout.php
> +		$cartPrice         = ( $areCouponsApplied && $cartTotalPrice > $cartContentPrice ) ? $cartContentPrice : $cartTotalPrice;
Nešlo by getCartContentPrice použít vždy a mít kód jednodušší a přehlednější?

2022-09-13 06:15 UTC, Mrakor commented on src/Packetery/Module/Checkout.php
> +		$cartPrice         = ( $areCouponsApplied && $cartTotalPrice > $cartContentPrice ) ? $cartContentPrice : $cartTotalPrice;
v dalsim ticketu do toho jeste vstoupi pocitani obsahu kosiku s DPH, takze pripadne zjednodusovani bych resil az tam.
zrejme vznikne samostana funkce.

2022-09-13 09:59 UTC, merged