PES-871 Round COD according to user setting before packet submit
Zasilkovna/WooCommerce pull request #282
Opened 2022-10-04 13:39 UTC by Mrakor

2022-10-13 05:06 UTC, packeta requested changes

2022-10-13 05:06 UTC, packeta commented on src/Packetery/Core/Helper.php
> +	public static function customRound( float $amount, int $roundingType, int $precision ): float {
Zaokrouhlování by si možná zasloužilo vlastní třídu.   Helper se rozrostl o 3 metody , které slouží pro zaokrouhlení, z toho je ale potřeba jen jedna jako public.

2022-10-13 06:18 UTC, Mrakor commented on src/Packetery/Core/Helper.php
> +	public static function customRound( float $amount, int $roundingType, int $precision ): float {
:heavy_check_mark:

2022-10-19 09:47 UTC, FJiskra requested changes

2022-10-19 10:37 UTC, jan-potuznik-z commented on src/Packetery/Core/Rounder.php
> +			return ceil( (float) ( (string) $amount ) );
Podle mě je podstatné, aby metoda respektovala $roundingType, kontrolu na znaménko si může její uživatel udělat před použitím.

2022-11-01 08:47 UTC, merged