PES-1051: "Maximum COD value" carrier setting
Zasilkovna/WooCommerce pull request #295
Opened 2022-10-24 13:09 UTC by jan-potuznik-z

2022-10-27 09:57 UTC, FJiskra requested changes

2022-10-27 09:57 UTC, FJiskra commented on readme.txt
> +Added: New setting of a carrier: "Maximum COD value"
Toto se zadává až těsně před vydáním verze. Proto je u ticketu položka "Changelog".

2022-11-01 12:04 UTC, FJiskra requested changes

2022-11-01 12:23 UTC, jan-potuznik-z commented on src/Packetery/Module/Carrier/OptionsPage.php
> +			->addFilter(
Ano funguje, je to analogické validaci hmotnosti.

2022-11-01 12:25 UTC, jan-potuznik-z commented on src/Packetery/Module/Carrier/OptionsPage.php
> +				function ( float $value ) {
Na návratový typ nám 7.2 nestačí.

2022-11-01 12:47 UTC, FJiskra requested changes

2022-11-01 12:47 UTC, FJiskra commented on src/Packetery/Module/Carrier/OptionsPage.php
> +			->addFilter(
Nefunguje. Stránka se přenačte. Pravidlo greaterThan musíš přidat ještě před ->addFilter()

2022-11-01 12:47 UTC, FJiskra commented on src/Packetery/Module/Carrier/OptionsPage.php
> +				static function ( float $value ) {
návratový typ tam nejde dát?

2023-03-01 11:24 UTC, FJiskra commented on src/Packetery/Module/Checkout.php
> +		// TODO: fees can't be determined at this time. Provide new filter for the user?
Hádám, že metoda se volá po potvrzení údajů v pokladně zákazníkem. Pokladna v takovém případě ví výši poplatků. Šlo by poplatky vzít z odeslaných formulářových polí a nebo ze session?

Osobně bych zkusil překalkulovat košík. Tuším metodu "calculate_shipping".

Pokud se logika zacyklí, tak bych zkoumal proč a jestli to někde nejde lépe opodmínkovat.

V nejhoším případě by to mělo jít předat Javascriptem v pokladně. Ale to by bylo ošklivé.

2023-03-15 09:35 UTC, FJiskra approved these changes

2023-03-20 09:29 UTC, jan-potuznik-z commented on public/debounce.js
Nebylo by to lepší jako součást checkout.js, když to zatím jinde nepoužíváme?

2023-03-20 09:29 UTC, jan-potuznik-z commented on src/Packetery/Module/Checkout.php
> +		return (float) WC()->cart->get_total( 'raw' );
Tato metoda mi přijde naprosto zbytečná.

2023-03-20 09:29 UTC, jan-potuznik-z commented on src/Packetery/Module/Checkout.php
> +		return (float) WC()->cart->get_shipping_total() + (float) WC()->cart->get_shipping_tax();
Tato metoda zbytečně prodlužuje a znepřehledňuje již tak dlouhou třídu.

2023-03-27 11:50 UTC, merged