PES-1059_packetStatus_entity
Zasilkovna/WooCommerce pull request #298
Opened 2022-10-27 12:25 UTC by jan-potuznik-z

2022-10-31 12:40 UTC, FJiskra requested changes

2022-10-31 12:40 UTC, FJiskra commented on src/Packetery/Module/Order/PacketSynchronizer.php
> -			'received data'          => true,
Jsou vyřešené výchozí hodnoty na všech místech v pluginu? Včetně Provider::getStatusSyncingPacketStatuses() ?

2022-10-31 12:40 UTC, FJiskra commented on src/Packetery/Module/Order/PacketSynchronizer.php
> +			'received data'          =>
Přesunout do třídy PacketStatus jako konstantu?.

2022-11-01 06:48 UTC, jan-potuznik-z commented on src/Packetery/Core/Entity/PacketStatus.php
> +	public $name;
Jak si to představuješ? Sice se momentálně nikde nepoužívá, ale podle mě tam jako public patří.

2022-11-01 11:30 UTC, FJiskra commented on src/Packetery/Core/Entity/PacketStatus.php
> +	public $name;
Order entita má třídní proměnné privátní. Zde to prosím udělejme stejně.

2022-11-01 11:46 UTC, FJiskra requested changes

2022-11-01 11:46 UTC, FJiskra commented on src/Packetery/Module/Options/Provider.php
> +				function ( $packetStatus ) {
Prosím přidat typ argumentu, návratový typ a "static"

2022-11-03 07:46 UTC, FJiskra requested changes

2022-11-03 07:46 UTC, FJiskra commented on src/Packetery/Module/Order/GridExtender.php
> +				echo esc_html( $statuses[ $order->getPacketStatus() ]->getTranslatedName() ?? $order->getPacketStatus() );
Operátor ?? nefunguje pro neexistující metody.

2022-11-03 07:46 UTC, FJiskra commented on src/Packetery/Module/Options/Provider.php
> +				static function ( $packetStatus ): bool {
Prosím přidat typ argumentu

2022-11-03 10:45 UTC, merged