Pes 1090 delayed dispatch of packet
Zasilkovna/WooCommerce pull request #312
Opened 2022-11-15 15:46 UTC by MMozola

2022-11-22 07:52 UTC, packeta requested changes

2022-11-22 12:37 UTC, packeta requested changes

2022-11-22 12:37 UTC, packeta commented on src/Packetery/Module/Order/Metabox.php
> +							->addRule( [ FormValidators::class, 'dateIsLater' ], __( 'Date must be in future', 'packeta' ), wp_date( 'Y-m-d' ) );
Bylo by pěkné, kdyby v chybové hlášce byl uvedený i minimální datum platnosti.  Např. Datum musí být od XX.XX.XX

2022-11-22 12:37 UTC, packeta commented on public/admin-order-detail.js
> +		$( 'input[name="packetery_deliver_on"]' ).datepicker( 'option', 'minDate', new Date() );
Bylo by možné sjednotit nastavení datepickeru na jedno místo ?

2022-11-22 12:37 UTC, packeta commented on src/Packetery/Core/Entity/Order.php
> +	private $deliverOn;
DateTimeImmutable nebo null

2022-11-22 12:37 UTC, packeta commented on src/Packetery/Module/Order/Repository.php
> +			'deliver_on'        => $order->getDeliverOn() ? $order->getDeliverOn()->format( Plugin::DATEPICKER_FORMAT ) : null,
$order->getDeliverOn()->format( Plugin::DATEPICKER_FORMAT ) zkusit vyčlenit do nějakého Helperu.

2022-11-23 14:32 UTC, jan-potuznik-z commented on src/Packetery/Module/FormValidators.php
> +	 * @param \PacketeryNette\Forms\Controls\BaseControl $input Form input.
Když už tam ten use statement je, použij ho.

2022-11-23 14:32 UTC, jan-potuznik-z commented on template/order/modal-template.latte
> +
Asi zbytečná změna.

2022-11-23 14:32 UTC, jan-potuznik-z commented on template/order/grid-column-packetery.latte
> +       'test' => $order->isPacketaInternalPickupPoint() ? 'internal' : 'external',
Prosím přejmenovat. I v modal-template.latte

2022-11-24 07:57 UTC, MMozola commented on src/Packetery/Core/Helper.php
> +	public static function getStringFromDateTime( ?\DateTimeImmutable $date, string $format ): ?string {
dle dokumentace nette by to mělo být použité staticky https://doc.nette.org/en/forms/validation#toc-custom-rules-and-conditions

2022-11-24 09:15 UTC, jan-potuznik-z commented on src/Packetery/Module/Order/GridExtender.php
> +						'helper'           => new Helper(),
Stále předáváš helper do šablony, teď úplně zbytečně, jestli dobře vidím.

2022-11-24 09:15 UTC, jan-potuznik-z commented on template/order/modal-template.latte
> +</script>
Zbytečná změna, která jde proti best practice.

2022-11-24 09:15 UTC, jan-potuznik-z commented on src/Packetery/Core/Helper.php
> +	public static function getStringFromDateTime( ?\DateTimeImmutable $date, string $format ): ?string {
Ty je ale nepoužíváš ve třídě FormValidators.

2022-11-25 07:31 UTC, jan-potuznik-z commented on src/Packetery/Module/Order/Metabox.php
> +		$order->setCod( is_numeric( $values[ self::FIELD_COD ] ) ? $this->helper->simplifyFloat( $values[ self::FIELD_COD ], 10 ) : null );
simplifyFloat je statická, IDE by ti mělo svítit. Tato chyba by nehrozila, pokud bys místo hromadných náhrad použil usages. Metody, které dělal Filip uděláme dynamické případně v jiném ticketu.

2022-11-28 10:24 UTC, merged