PES-1080: Disable COD if a shipping method that does not support COD …
Zasilkovna/WooCommerce pull request #325
Opened 2022-12-01 11:54 UTC by jan-potuznik-z

…is selected at checkout

2022-12-01 13:27 UTC, FJiskra requested changes

2022-12-01 15:29 UTC, jan-potuznik-z commented on src/Packetery/Module/Checkout.php
> +		if ( ! is_admin() ) {
Nejde, nastane Call to undefined function is_checkout()

2022-12-09 12:38 UTC, jan-potuznik-z commented on src/Packetery/Module/Carrier/OptionsPage.php
> +		if ( $carrier->supportsCod() ) {
Není, upravím.

2022-12-12 10:55 UTC, FJiskra requested changes

2022-12-12 10:55 UTC, FJiskra commented on src/Packetery/Module/Carrier/OptionsPage.php
> +		if ( isset( $options['order_price'] ) ) {
Je toto správně?

2022-12-12 10:55 UTC, FJiskra commented on src/Packetery/Module/Checkout.php
> +		if ( null === $paymentMethod || false === $this->isCodPaymentMethod( $paymentMethod ) ) {
Jsi si jistý, že WC()->session->get( 'chosen_payment_method' ) nemůže vrátit false ? Já bych se snažil nedělat změny navíc.

2023-01-02 11:56 UTC, merged