Pes 1104 gridextender sql optimization
Zasilkovna/WooCommerce pull request #332
Opened 2022-12-12 08:58 UTC by MMozola

2022-12-13 09:28 UTC, FJiskra requested changes

2022-12-13 13:04 UTC, MMozola commented on src/Packetery/Module/Order/Repository.php
> +				$orderIds
není

2022-12-14 10:54 UTC, FJiskra requested changes

2022-12-14 10:54 UTC, FJiskra commented on src/Packetery/Module/Order/Repository.php
> +	public function getOrdersByIds( array $orderIds ): ?array {
Kdy metoda vrací null?

2022-12-14 10:54 UTC, FJiskra commented on src/Packetery/Module/Order/GridExtender.php
>  			if ( null === self::$orderCache ) {
Je tato podmínka potřeba?

2022-12-14 11:13 UTC, MMozola commented on src/Packetery/Module/Order/GridExtender.php
>  			if ( null === self::$orderCache ) {
není

2022-12-16 08:37 UTC, packeta requested changes

2022-12-16 08:37 UTC, packeta commented on src/Packetery/Module/Order/Repository.php
> +	 * @return array
Prosím uveď co konkrétně co je v poli za návratovou hodnotu.

2022-12-22 06:53 UTC, packeta requested changes

2023-01-02 11:54 UTC, jan-potuznik-z commented on src/Packetery/Module/Order/GridExtender.php
> +		if ( isset( $GLOBALS['posts'] ) && is_array( $GLOBALS['posts'] ) ) {
Nebylo by hezčí použít global $posts - jako používáme jinde v pluginu?

2023-01-13 10:31 UTC, jan-potuznik-z commented on src/Packetery/Module/Order/Repository.php
> +			SELECT o.* FROM `' . $wpdbAdapter->packetery_order . '` o
Table alias nemá backticks, ale stejně je zbytečný, dej ho prosím pryč. Preferoval bych úpravu formátování, aby ten string začínal 'SELECT

2023-01-16 08:44 UTC, merged