PES-1141_disallow_carriers_by_product_fix
Zasilkovna/WooCommerce pull request #334
Opened 2022-12-12 17:24 UTC by MMozola

2022-12-15 10:05 UTC, FJiskra requested changes

2022-12-16 11:16 UTC, jan-potuznik-z commented on src/Packetery/Module/Carrier/Repository.php
> +				$carrierId        = $carrierOptions->getOptionId();
Přejmenuj prosím tu proměnnou.

2022-12-19 12:12 UTC, packeta requested changes

2022-12-19 12:12 UTC, packeta commented on src/Packetery/Module/Checkout.php
> +			if ( in_array( $optionId, $disallowedShippingRateIds, true ) || in_array( $optionIdFallback, $disallowedShippingRateIds, true ) ) {
$optionIdFallback je hack , který v kódu nechceme.  Prosím dát pryč a problém vyřešit formou migrací.

2022-12-20 09:53 UTC, jan-potuznik-z commented on src/Packetery/Module/Upgrade.php
> +		$productsIdsRows = $wpdb->get_results( $wpdb->prepare( 'SELECT post_id FROM %s WHERE meta_key = %s', $wpdb->prefix . 'postmeta', $metaKey ) );
Názvy sloupců prosím důsledně do backticks (`). Viděl bych je raději i u názvu tabulky.

2022-12-20 09:53 UTC, jan-potuznik-z commented on src/Packetery/Module/Upgrade.php
> +		$productsIdsRows = $wpdb->get_results( $wpdb->prepare( 'SELECT post_id FROM %s WHERE meta_key = %s', $wpdb->prefix . 'postmeta', $metaKey ) );
Můžeš použítt rovnou $wpdb->postmeta

2022-12-20 16:03 UTC, packeta requested changes

2022-12-20 16:03 UTC, packeta commented on src/Packetery/Module/Upgrade.php
> +			update_post_meta( $productId, Product\Entity::META_DISALLOWED_SHIPPING_RATES, $newMeta );
A druhý dotaz mám k metodě migrateDisallowedCarriersByProducts() - https://github.com/Zasilkovna/WooCommerce/pull/334/files#diff-3c47ed004341b94a82afbae35cc2c04f771031d4af4eeffb4275fa4da268f37aR422 - proč je potřeba volat update_post_meta() nad každým produktem , jehož ID získáme z metody getProductsIdsWithExistingMeta() ? Nestačilo by aktualizovat jen ty produkty u kterých jsme našli duplicitní prefix packetery_carrier_packetery_carrier_ ? a ten pak opravit ? Pokud jsem správně pochopil z našich standupů, tak problém není u všech produktů , které mají omezení dopravce, ale jen u těch produktů, které byly editovány ve verzi 1.4.1.

2022-12-20 16:03 UTC, packeta commented on src/Packetery/Module/Upgrade.php
> +		$productsIdsRows = $wpdb->get_results(
nejde pro získání pole s post_id použít wpdb->get_col() ?

2022-12-28 08:17 UTC, packeta requested changes

2022-12-28 08:29 UTC, MMozola commented on src/Packetery/Module/Upgrade.php
> +		$carrierPrefix           = 'packetery_carrier_';
Tohle bych tu nechal kvůli čitelnosti. Přijde mi hezčí mít ty proměnný takhle definovaný, než pracovat jednou s proměnnou a jednou tam mít string na přímo. Další věc je, že hned vidím, co ten string znamená.

2022-12-28 08:31 UTC, packeta requested changes

2022-12-28 08:31 UTC, packeta commented on src/Packetery/Module/Upgrade.php
> +		$likeQuery  = '%' . $duplicatedPrefix . '%';
Tak jsem si našel, že se to opravdu takto používá.  V tom případě to tak nechme, jen bych se zbavil property $likeQuery a ten string byl dal rovnou jako parametr $wpdb->prepare. Používá se jen na jednom místě a proto mi připadá zbytečný.

2023-01-10 12:36 UTC, jan-potuznik-z commented on src/Packetery/Module/Upgrade.php
> +		$carrierPrefix           = 'packetery_carrier_';
Já bych tam použil Checkout::CARRIER_PREFIX

2023-01-12 20:36 UTC, packeta commented on src/Packetery/Module/Upgrade.php
> +		$carrierPrefix           = 'packetery_carrier_';
@jan-potuznik-z souhlas. uprav to prosím

2023-01-16 09:49 UTC, merged