PES-288: bulk order submit
Zasilkovna/WooCommerce pull request #35
Opened 2021-09-06 14:52 UTC by jan-potuznik-z

2021-09-09 13:21 UTC, packeta requested changes

2021-09-10 07:12 UTC, jan-potuznik-z commented on packetery/src/Packetery/Api/Soap/Packet.php
> +			$requiresSize = $this->carrierRepository->requiresSize( $carrierId );
Upraveno na value object.

2021-09-10 07:14 UTC, jan-potuznik-z commented on packetery/src/Packetery/Api/Soap/Packet.php
> +			foreach ( $order->get_items() as $item ) {
Žádná nevýhoda mě nenapadá, košík má navíc na hmotnost metodu, takže se té konstrukce získání hmotnosti z objednávky zbavíme.

2021-09-10 10:18 UTC, packeta requested changes

2021-09-10 10:18 UTC, packeta commented on packetery/src/Packetery/Api/OrderClient.php
> +	private function getContactInfo( WC_Order $order, array $orderData ):array {
proč tato funkce nevrací value object?  IDE by krásně napovídalo .

2021-09-10 10:18 UTC, packeta commented on packetery/src/Packetery/Api/Soap/Packet.php
> +	public function createPacket( string $apiPassword, array $attributes ):stdClass {
nepoužívejme prosím stdClass, ale vlastní value object

2021-09-10 10:28 UTC, jan-potuznik-z commented on packetery/src/Packetery/Carrier/Carrier.php
> +	/**
Přidat řádky před komentáře.

2021-09-10 10:28 UTC, jan-potuznik-z commented on packetery/src/Packetery/Carrier/Carrier.php
> +	public function getId(): int {
Probrat get vs. is.

2021-09-10 10:30 UTC, jan-potuznik-z commented on packetery/src/Packetery/Carrier/Carrier.php
> +	public function getIsPickupPoints(): bool {
Probrat get vs. is.

2021-09-13 11:27 UTC, FJiskra commented on packetery/src/Packetery/Carrier/Carrier.php
> +class Carrier {
přejmenovat z Packetery\Carrier\Carrier na Packetery\Carrier\Entity. Ať je to jednotné s Packetery\Order\Entity

2021-09-13 11:53 UTC, FJiskra commented on packetery/src/Packetery/Api/OrderClient.php
> +class OrderClient {
spíš bych přesunul do Packetery\Order\ApiClient

2021-09-13 13:59 UTC, jan-potuznik-z commented on packetery/src/Packetery/Api/Soap/Base.php
> +class Base {
BaseClient?

2021-09-29 13:49 UTC, packeta requested changes

2021-09-29 14:04 UTC, merged