PES-1288, PES-1355: filters to modify the HTML generated on the frontend
Zasilkovna/WooCommerce pull request #375
Opened 2023-04-13 09:19 UTC by jan-potuznik-z

2023-04-28 13:50 UTC, FJiskra requested changes

2023-04-28 13:50 UTC, FJiskra commented on README.md
> +		$footerHtml  = '<p>' . $pickupPoint->getName() . '</p>';
tady a jinde bych naznačil že by měli escapovat hodnoty pomocí htmlentities()

2023-04-28 13:50 UTC, FJiskra commented on src/Packetery/Module/Checkout.php
> +		Helper::renderString( (string) apply_filters( 'packeta_widget_button_row', $widgetButtonRowHtml ) );
Latte parametry zde předávat nechceme?

2023-04-28 15:52 UTC, jan-potuznik-z commented on README.md
> +		$footerHtml = '<p>' . $address->getStreet() . ' ' . $address->getHouseNumber() . ', ' . $address->getCity() . ' ' . $address->getZip() . '</p>';
Ty objekty se potom dál nepoužívají, takže bych řekl, že to nevadí.

2023-05-02 07:14 UTC, jan-potuznik-z commented on src/Packetery/Module/Checkout.php
> +		Helper::renderString( (string) apply_filters( 'packeta_widget_button_row', $widgetButtonRowHtml ) );
Probráno, zatím ne.

2023-05-05 09:41 UTC, merged