Pes 1182 selected pickup point saved in db
Zasilkovna/WooCommerce pull request #386
Opened 2023-04-20 15:03 UTC by jan-potuznik-z

2023-04-26 12:58 UTC, FJiskra requested changes

2023-04-26 12:58 UTC, FJiskra commented on public/checkout.js
> +					// TODO: handle error. Controller does not expect errors happening.
TODO odstranit?

2023-04-26 13:21 UTC, jan-potuznik-z commented on config/config.neon
> +	- Packetery\Module\Api\OrderController
To je otázkou dalšího vývoje, který byl rámci tohoto požadavku zatím pozastaven.

2023-04-28 12:42 UTC, FJiskra requested changes

2023-04-28 12:42 UTC, FJiskra commented on src/Packetery/Module/Api/Internal/CheckoutController.php
> +			$this->checkout->getTransientNamePacketaCheckoutData(),
Pokladna si pamatuje předešlý výběr zákazníka díky JS proměnné. Pokud si zákazník vybere VM a pak změní způsob dopravy a ověří adresu, tak se transient s vybraným VM přepíše daty té ověřené adresy. Pokud zákazník následně změní svou volbu dopravy zpět na PP možnost, tak v pokladně se zobrazí předešle zvolené VM, ale transient ho mít nebude, protože VM data se ukládají jenom při potvrzení volby v otevřeném widgetu.

Doporučuji párovat rateId se zaslanými daty a slučovat je s daty transientu. Neřešilo se něco podobného ve VirtueMartu?

2023-05-09 09:46 UTC, FJiskra requested changes

2023-05-09 09:46 UTC, FJiskra commented on public/checkout.js
> +					pickupPointDataToSave.packetery_carrier_id = carrierRateId;
nejsou packetery_carrier_id a carrierRateId významově odlišné hodnoty?

packetery_carrier_id má obsahovat hodnotu z objektu point, který předává widget při zvolení VM. Viz Attribute::$pickupPointAttrs

carrierRateId je shipping rate id

2023-05-12 12:06 UTC, merged