PES-2062: Implementation of SCSS preprocessor
Zasilkovna/WooCommerce pull request #560
Opened 2024-05-24 11:07 UTC by DBelka

Implemented a new NPM library for SCSS, and adjusted the structure of the codebase to facilitate the changes.

2024-05-28 08:40 UTC, jan-potuznik-z commented on package.json
> +    "watch:sass": "sass --watch public/scss:public/css --no-source-map --style compressed"
Přidal bych dev verzi příkazu s mapováním a map soubory bych dal do gitignore. Zjednodušší nám to vývoj.

2024-05-28 08:40 UTC, jan-potuznik-z commented on public/scss/front.scss
> +.packeta-widget-button {
Asi došlo k nějakému omylu. Takhle je to přeci horší, než výsledné CSS. Viz https://sass-lang.com/documentation/style-rules/ Připomínka se týká všech SCSS souborů.

2024-06-07 08:39 UTC, xpavp03 requested changes

2024-06-07 08:39 UTC, xpavp03 commented on public/scss/_variables.scss
tabulátory, prosím

2024-06-07 08:39 UTC, xpavp03 commented on public/scss/admin.scss
tabulátory, prosím + front.scss taky

2024-06-07 09:00 UTC, xpavp03 commented on public/scss/admin.scss
Možná chybí pravidlo v CodeSnifferu.

2024-06-07 09:06 UTC, xpavp03 commented on public/scss/admin/_custom-declaration.scss
Jarda už .editorconfig vytvořil.

2024-06-07 10:29 UTC, jan-potuznik-z commented on public/scss/admin.scss
CodeSniffer s WP pravidly scss neřeší, otestováno.

2024-08-13 12:11 UTC, zemekoule approved these changes

2024-08-13 12:12 UTC, merged