PES-2252: Remove cardelivery when suppressed in product and category
Zasilkovna/WooCommerce pull request #593
Opened 2024-08-27 13:25 UTC by DBelka

Added extra logic to show/hide Car Delivery options in Product and Product Category.

2024-08-28 07:09 UTC, zemekoule requested changes

2024-08-28 10:02 UTC, DBelka commented on src/Packetery/Module/Product/DataTab.php
> +			if ( false === $this->carDeliveryConfig->isEnabled() && in_array( OptionPrefixer::removePrefix( $carrier['option_id'] ), Carrier::CAR_DELIVERY_CARRIERS, true ) ) {
Neni problem. Upraveno pro lepsi citelnost.

2024-08-28 14:11 UTC, zemekoule requested changes

2024-08-28 14:11 UTC, zemekoule commented on src/Packetery/Module/Product/DataTab.php
> +			if ( $this->carDeliveryConfig->isDisabled() && in_array( OptionPrefixer::removePrefix( $carrier['option_id'] ), Carrier::CAR_DELIVERY_CARRIERS, true ) ) {
Stejnou podmínku máš na dvou místech.

2024-08-29 15:17 UTC, DBelka commented on src/Packetery/Module/Product/DataTab.php
> +			if ( $this->carDeliveryConfig->isDisabled() && in_array( OptionPrefixer::removePrefix( $carrier['option_id'] ), Carrier::CAR_DELIVERY_CARRIERS, true ) ) {
Posunuto do jedne metody.

2024-08-30 11:36 UTC, zemekoule approved these changes

2024-08-30 16:16 UTC, merged