PES-2320: correct display for Packeta Pick-up Point carrier in countr…
Zasilkovna/WooCommerce pull request #629
Opened 2024-10-29 10:27 UTC by jan-potuznik-z

…ies with external pickup points

2024-10-29 13:08 UTC, Karpec requested changes

2024-10-29 13:08 UTC, Karpec commented on src/Packetery/Module/Carrier/PacketaPickupPointsConfig.php
> +					if ( strpos( $vendorCode, $country ) === 0 ) {
Viz. call - Přidat groupy rovnou ke carriers než takhle to vyzobávat přes strpos a substr a podívat se na zemi dopravce.

2024-10-30 09:47 UTC, Karpec requested changes

2024-10-30 09:47 UTC, Karpec commented on tests/Module/Carrier/PacketaPickupPointsConfigTest.php
> +		$featureFlagProvider->method( 'isSplitActive' )
Tohle bych dal do konrkétního testu nebo bych tu metodu create přejmenoval, protože už nastavuješ tomu mocku nějaký stav. Co když budu chtít otestovat případ, kdy mi metoda isSplitActive vrátí false?

2024-10-30 10:47 UTC, Karpec approved these changes

2024-10-30 11:13 UTC, zemekoule requested changes

2024-10-30 11:13 UTC, zemekoule commented on src/Packetery/Module/WidgetOptionsBuilder.php
> +	private function getWidgetVendorsParam( string $carrierId, string $country, ?array $vendorGroups ): array {
Napsal bych test i na tuto metodu, protože logika metody se docela změnila.

2024-10-31 04:26 UTC, zemekoule approved these changes

2024-10-31 04:26 UTC, merged