PES-2323: new composer commands
Zasilkovna/WooCommerce pull request #640
Opened 2024-11-05 09:30 UTC by jan-potuznik-z

2024-11-05 10:45 UTC, Karpec requested changes

2024-11-05 10:45 UTC, Karpec commented on composer.json
> +            "@phpstan-72",
phpstan:

2024-11-05 10:45 UTC, Karpec commented on composer.json
> +        "build-pot": "bash build-pot.sh",
build:

2024-11-05 10:45 UTC, Karpec commented on composer.json
> +            "@tests-unit",
podle mě by se měl spustit phpstan ještě před testy. Testy budou časem bobnat a budeš čekat třeba X minut "zbytečně", když ti to pak spadne na phpstanu a budeš se vrtat ve finále stejně v kodu a potažmo v testech

2024-11-06 17:23 UTC, mzk commented on composer.json
> +            "@check:ec"
ec by měl být první, protože je nejrychlejší. pak phpcs, pak phpstan a nakonec phpunit testy.

2024-11-07 11:47 UTC, merged