PES-2341, PES-2413, PES-2420, PES-2597, PES-2621: uninstall refactor
Zasilkovna/WooCommerce pull request #683
Opened 2024-12-06 15:08 UTC by FJiskra

2024-12-09 08:45 UTC, jan-potuznik-z commented on src/Packetery/Module/Uninstaller.php
> + * Uninstaller class.
Prosím z třídy a veškerého nového kódu odstranit komentáře, které nenesou přidanou hodnotu.

2024-12-09 08:45 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +		return $this->deleteByPrefix( $transientPrefix );
V databázi zůstanou timeout záznamy ke smazaným transientům. Určitě by měla být použita funkce delete_transient.

2024-12-09 08:45 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +				"DELETE FROM {$this->wpdbAdapter->options}
I zde bych použil funkci delete_option.

2024-12-09 12:02 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +		return $this->deleteByPrefix( $transientPrefix );
Jestli neexistuje vhodná funkce WP, tak tahat z db v repozitáři a v rámci jiné třídy mazat dedikovanou funkcí. Stejně tak pro options. Analýza i návrh řešení jsou v tvých rukou.

2024-12-11 09:27 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +			$transientNames[] = preg_replace( '~^_transient_~', '', $optionName, 1 );
Zbytečný parametr limit.

2024-12-11 09:27 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +	public function getAllOptionNamesByPrefixes( array $prefixes ) {
Chybí návratový typ.

2024-12-11 09:27 UTC, jan-potuznik-z commented on src/Packetery/Module/Uninstaller.php
> +		foreach ( $transientsToDelete as $optionName ) {
Protože jde o refactor, udělej to stejně i v metodě `deleteExpiredTransientsByPrefix`, abychom se zbavili mazání SQL dotazem.

2025-01-02 09:48 UTC, zemekoule requested changes

2025-01-02 09:48 UTC, zemekoule commented on src/Packetery/Module/Uninstaller.php
> +			delete_option( $optionName );
Neprováděl bych mazání všech options, které mají prefix "packetery_" nebo "packeta_".  Můžeme se lehce stát, že smažeme nastavení, které nepochází z našeho pluginu.  Mazal bych konkrétní názvy options, které v pluginu používáme.

2025-01-02 09:48 UTC, zemekoule commented on src/Packetery/Module/Options/Repository.php
> +	public function getAllOptionNamesByPrefixes( array $prefixes ): array {
Jednotlivé options bych netahal přímo z DB, ale využil bych metodu WP wp_load_alloptions() - https://developer.wordpress.org/reference/functions/wp_load_alloptions/.   Pokud by WP změnil způsob načítání options, museli bychom dělat změny.  Použití funkce WP je tak bezpečnější.

2025-01-02 11:22 UTC, zemekoule commented on src/Packetery/Module/Uninstaller.php
> +		foreach ( $transientsToDelete as $optionName ) {
nemažou se takto jen expirované transienty ? nám jde o to, aby náš plugin po sobě "uklidil", pokud se uživatel rozhodne odstranit.  Tedy aby smazal i transienty, které nejsou expirované.

2025-01-02 11:23 UTC, zemekoule commented on src/Packetery/Module/Options/Repository.php
> +	public function getAllOptionNamesByPrefixes( array $prefixes ): array {
moc jsem tuto funkci nezkoumal, pokud není dostačující, zkus se podívat, jestli najdeš jinou, vhodnější.

2025-01-06 09:53 UTC, Karpec commented on src/Packetery/Module/Order/CollectionPrint.php
> +
mezera navíc :)

2025-01-06 11:04 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/TransientPurger.php
> +				wc_delete_expired_transients();
Opravdu si můžeme dovolit mazat transienty WP a jiných pluginů?

2025-01-06 11:04 UTC, jan-potuznik-z commented on src/Packetery/Module/Uninstaller.php
> +				Checkout::TRANSIENT_CHECKOUT_DATA_PREFIX,
Co uložit názvy a prefixy transientů do dedikované třídy a tím zajistit, že bude řešení vyhovovat poslední větě zadání?

2025-01-07 11:19 UTC, jan-potuznik-z commented on src/Packetery/Module/Uninstaller.php
> +				Checkout::TRANSIENT_CHECKOUT_DATA_PREFIX,
Mnou navrhovaná tříba by významně snížila riziko, že někdo zapomene svůj nový transient přidat do Uninstalleru. Kód uninstalleru by byl hezčí.

2025-01-07 14:07 UTC, zemekoule commented on src/Packetery/Module/Options/TransientPurger.php
> +				wc_delete_expired_transients();
mazání všech expirovaných transientů bez ohledu na to z jakého jsou pluginu bych opravdu nedělal.  můžeme smazat něco, co eshop z nějakého důvodu potřebuje a co nám nepatří.  WC je také smaže až když to někdo chce a klikne na tlačítko.  Smazal bych pouze naše transienty.  Ať už jsou expirované nebo nejsou

2025-01-07 14:13 UTC, jan-potuznik-z commented on src/Packetery/Module/Uninstaller.php
> +	 * Drops all plugin tables and options for a single site.
upravil bych na `tables, options and transients` - 2 výskyty

2025-01-08 09:03 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/TransientPurger.php
> +	 * @param Repository $optionsRepository Options repository.
Celý komentář je možné dát pryč.

2025-01-08 09:03 UTC, jan-potuznik-z commented on src/Packetery/Module/Uninstaller.php
> +		if ( is_multisite() ) {
Pro všechny WP/WC metody v této třídě použít adaptery.

2025-01-08 09:25 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +				AND `option_name` = CONCAT( '_transient_timeout_', SUBSTRING( a.option_name, 12 ) )
Mně to hází `Unknown column 'a.option_name' in 'where clause' `

2025-01-08 14:48 UTC, jan-potuznik-z commented on src/Packetery/Module/Options/Repository.php
> +				"SELECT SUBSTRING(a.`option_name`, 12)
Doplnil bych backticks v celém dotazu.

2025-01-08 14:48 UTC, jan-potuznik-z commented on src/Packetery/Module/Options.php
> +class Options {
Udělal bych to jako Packetery\Module\Options\OptionNames a odstranil bych z názvů konstant zbytečné prefixy.

2025-01-10 08:29 UTC, zemekoule commented on src/Packetery/Module/Transients.php
> +class Transients {
uděláme v jiném ticketu

2025-02-07 13:31 UTC, Karpec approved these changes

2025-02-11 11:04 UTC, jan-potuznik-z approved these changes

2025-02-28 17:40 UTC, zemekoule approved these changes

2025-02-28 17:40 UTC, merged